### ISSUE TITLE
1.4.9 crashes

### ISSUE THREAD

**Issue by CeratoRaptor** [Guild-Hall/MHFC#29]
Whenever I launch the game, it always crashes and shows this report

---- Minecraft Crash Report ----
// My bad.

Time: 3/15/20 5:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Monster Hunter Frontier Craft (mhfc)
Caused by: java.lang.NoSuchFieldError: GROUND
at mhfc.net.common.block.decoration.BlockDirt.<init>(BlockDirt.java:14)
at mhfc.net.common.core.registry.MHFCBlockRegistry.<init>(MHFCBlockRegistry.java:88)
at mhfc.net.common.core.registry.MHFCBlockRegistry$$Lambda$85/2090952225.get(Unknown Source)
at mhfc.net.common.core.registry.RegistryWrapper.register(RegistryWrapper.java:21)
at mhfc.net.common.core.registry.RegistryWrapper$1.onPhaseStart(RegistryWrapper.java:49)
at mhfc.net.common.core.registry.RegistryWrapper$1.onPhaseStart(RegistryWrapper.java:46)
at mhfc.net.common.util.services.Services$PhaseEntry$ServicePhaseEntry.enter(Services.java:236)
at mhfc.net.common.util.services.Services$PhaseEntry.enterServices(Services.java:328)
at mhfc.net.common.util.services.Services.enterPhase(Services.java:554)
at mhfc.net.common.util.services.Services.access$300(Services.java:18)
at mhfc.net.common.util.services.Services$PhaseEntry.enterPhase(Services.java:386)
at mhfc.net.MHFCMain.onPreInit(MHFCMain.java:175)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 469987752 bytes (448 MB) / 805306368 bytes (768 MB) up to 6442450944 bytes (6144 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=64M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.4.2750 7 mods loaded, 7 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
|:----- |:--------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
| UCH | minecraft | 1.12.2 | minecraft.jar | None |
| UCH | mcp | 9.42 | minecraft.jar | None |
| UCH | FML | 8.0.99.99 | forge-1.12.2-14.23.4.2750.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCH | forge | 14.23.4.2750 | forge-1.12.2-14.23.4.2750.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCH | mcanm | 2.7.4.149 | mcanm-2.7.4.149-a7cc834+1.12.2 (2).jar | None |
| UCH | worldedit | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (2).jar | None |
| UCEE | mhfc | 1.4.8.1508-1.12.2+1.12.2 | mhfc-1.4.9 (2).jar | None |

Loaded coremods (and transformers):
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.84' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

 please fix this.

**Comment by LLjo** [comment]
exact same problem here
